import {library} from '@fortawesome/fontawesome-svg-core';
import {
    faAngleDown,
    faAngleUp,
    faArrowRight,
    faArrowRotateLeft,
    faBars,
    faBolt,
    faCaretRight,
    faCheck,
    faCheckCircle,
    faChess,
    faCircle,
    faCircleNotch,
    faClock,
    faCodeBranch,
    faDiceD6,
    faFolder,
    faGears,
    faPlay,
    faPlus,
    faSeedling,
    faSquareArrowUpRight,
    faTable,
    faTimes,
    faTurnUp,
    faUser
} from "@fortawesome/free-solid-svg-icons";
import {faFile} from "@fortawesome/free-regular-svg-icons";

library.add(
    faBolt,
    faCheck,
    faPlay,
    faUser,
    faClock,
    faTimes,
    faSquareArrowUpRight,
    faAngleUp,
    faAngleDown,
    faBars,
    faDiceD6,
    faSeedling,
    faCaretRight,
    faPlus,
    faChess,
    faCircle,
    faCheckCircle,
    faCodeBranch,
    faArrowRight,
    faArrowRotateLeft,
    faFile,
    faFolder,
    faTurnUp,
    faCircleNotch,
    faTable,
    faGears
);
